### ISSUE TITLE
Error since CakePHP 2.3.1

### ISSUE THREAD

**Issue by flashnet69** [FMCorz/AclManager#12]
Hi,

Since update to CakePHP 2.3.1, ACO can't be generated...

In AclController.php, function _action (l. 377), i have an error because Cake requires a CakeRequest object and not an array.

I tried many thing but i can't resolve this problem...

Argument 1 passed to BaseAuthorize::action() must be an instance of CakeRequest ... Plugin/AclManager/Controller/AclController.php on line 386 and defined [CORE/Cake/Controller/Component/Auth/BaseAuthorize.php, line 112]

Can you help me to solve my problem ? Thanks in advance.

**Comment by FMCorz** [comment]
Thanks for reporting this.
Unfortunately I have very few time to work on this, and my knowledge of CakePHP has decrease over the last months. It'd be awesome if someone could submit a patch (maintaining backwards compatilibity of the plugin).

**Comment by FMCorz** [comment]
Hum... can you try this?

```
$params = array_merge(array('controller' => null, 'action' => null, 'plugin' => null), $request);
$request = new CakeRequest(null, false);
$request->addParams($params);
$authorizer = $this->_getAuthorizer();
```

**Comment by flashnet69** [comment]
It's works fine !!! I have modified and commited the AclController.
Thanks for your help !

**Comment by FMCorz** [comment]
Thanks for converting this to a pull request. Cheers!
