### ISSUE TITLE
Explain more step 1 and 4 

### ISSUE THREAD

**Issue by Harrrrry** [FMCorz/AclManager#25]
Hi,
I am very new for cakephp
Can you explain little bit more how to use step 1 and 4.
Getting error  Table aros_acos for model Permission was not found in datasource default.
Please,

**Comment by FMCorz** [comment]
I'm sorry, I haven't used CakePHP in years. You're better off asking in a forum.

**Comment by Harrrrry** [comment]
But the ACLmanager plugin for cakephp

**Comment by Harrrrry** [comment]
getting error AclNode::node() - Couldn't find Aro node identified by "Array ( [Aro0.model] => User [Aro0.foreign_key] => 5 ) "
