### ISSUE TITLE
Odd routing behavior 

### ISSUE THREAD

**Issue by thompsem** [FMCorz/AclManager#26]
I've recently installed Acl Manager, and so far it is a great tool. It is already saving me a ton of time. Although, I have noticed that If I am at a /acl_manager/acl page all of my urls suddenly have acl_manager prepended to the controller. 

For example if I am at acl_manager/acl/permissions and I want to navigate to my users index, my users url is now www.mysite.com/acl_manager/users/index which throws an error cause the acl_manager controller does not have a method for users. 

My navigation looks like:
$this->Html->link(__('Users'), array('controller' => 'users', 'action' => 'index'))

Is there some thing I have to change in my routing or how can I go about avoiding adding acl_manager to all my urls. 

Thanks for the help!

**Comment by houseoftech** [comment]
You could probably add 'plugin' => false to the URL array.
