### ISSUE TITLE
ACO updating is not being done correctly on Cake 2.1

### ISSUE THREAD

**Issue by afolgado** [FMCorz/AclManager#3]
When pressing "Update ACOs", it should update then the first time and report "0 acos updated" the following times. But it always find some ACOs to update.

The bug is on AclController.php, line 212: 

$aco = substr($aco, 0, -1);     // Remove trailing slash

Sometimes the $aco string doesn't bring a trailing slash, so it's wrongly altered.

Here's the fix:

if (substr($aco, -1) == '/') {
  $aco = substr($aco, 0, -1);       // Remove trailing slash
}

**Comment by FMCorz** [comment]
Thanks for reporting. This has been fixed.
