### ISSUE TITLE
Exception not catched in Cake 2.1

### ISSUE THREAD

**Issue by afolgado** [FMCorz/AclManager#4]
As CakePHP 2.1 uses exceptions for error handling in many functions instead of returning FALSE, the update_aros function is failing.

AclController.php, line 279:

$node = $Model->node();

If the node lookup fails it will throw a CakeException that must be caught. So the fix is:

```
            try {
                $node = $Model->node();
            } catch (CakeException $e) {
                $node = false;
            }
```

**Comment by FMCorz** [comment]
Fixed in last stable. Cheers!
