### ISSUE TITLE
Parse error, unclosed ; at AclController.php line 143

### ISSUE THREAD

**Issue by azrad** [FMCorz/AclManager#7]
This is happened when i download the zipball.

error message: Parse error: syntax error, unexpected T_VARIABLE in /Library/WebServer/Documents/bt1m/app/Plugin/AclManager/Controller/AclController.php on line 143

solution:
adding " ; " at line 142 solved the issue.

thanks

**Comment by FMCorz** [comment]
Thank you! Just fixed it now on the master branch.
